import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>TJ CORRETORA</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>TJ CORRETORA</h1>

        <div></div>
      </main>
    </div>
  );
}
