import Head from "next/head";
import Template from "../templates"

export default function Home() {
  return (
    <div>
      <Head>
        <title>TJ CORRETORA</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Template/> 
      </main>
    </div>
  );
}
